/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_trolsoft_jni_FileUtils */

#ifndef _Included_ru_trolsoft_jni_NativeFileUtils
#define _Included_ru_trolsoft_jni_NativeFileUtils
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_ru_trolsoft_jni_NativeFileUtils_getLibraryVersion
	(JNIEnv *, jclass);
/*
 * Class:     ru_trolsoft_jni_FileUtils
 * Method:    getLocalFileAttributes
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ru_trolsoft_jni_NativeFileUtils_getLocalFileAttributes
	(JNIEnv *, jclass, jstring);

JNIEXPORT jboolean JNICALL Java_ru_trolsoft_jni_NativeFileUtils_isLocalFileHidden
	(JNIEnv *, jclass, jstring);

JNIEXPORT jboolean JNICALL Java_ru_trolsoft_jni_NativeFileUtils_isLocalFileExecutable
	(JNIEnv *, jclass, jstring);

JNIEXPORT jboolean JNICALL Java_ru_trolsoft_jni_NativeFileUtils_isLocalDirectory
	(JNIEnv *, jclass, jstring);  


#ifdef __cplusplus
}
#endif
#endif
