# Настройки сборки
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# Версия приложения
app.version=1.0.0
app.vendor=Oleg Trifonov

# Путь к локальным библиотекам (для гибкости)
lib.runtime.dir=lib/runtime
lib.compile.dir=lib/compile
lib.test.dir=lib/test