/*
 * This file is part of muCommander, http://www.mucommander.com
 * Copyright (C) 2002-2012 Maxence Bernard
 *
 * muCommander is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * muCommander is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.mucommander.conf;

/**
 * 
 * @author Arik Hadas
 */
public enum TcPreference {
	CHECK_FOR_UPDATE(TcPreferences.CHECK_FOR_UPDATE),
	DATE_FORMAT(TcPreferences.DATE_FORMAT),
	DATE_SEPARATOR(TcPreferences.DATE_SEPARATOR),
	TIME_FORMAT(TcPreferences.TIME_FORMAT),
	LANGUAGE(TcPreferences.LANGUAGE),
	DISPLAY_COMPACT_FILE_SIZE(TcPreferences.DISPLAY_COMPACT_FILE_SIZE),
	CONFIRM_ON_QUIT(TcPreferences.CONFIRM_ON_QUIT),
	SHOW_SPLASH_SCREEN(TcPreferences.SHOW_SPLASH_SCREEN),
	LOOK_AND_FEEL(TcPreferences.LOOK_AND_FEEL),
	CUSTOM_LOOK_AND_FEELS(TcPreferences.CUSTOM_LOOK_AND_FEELS),
	ENABLE_SYSTEM_NOTIFICATIONS(TcPreferences.ENABLE_SYSTEM_NOTIFICATIONS),
	PREFERRED_ENCODINGS(TcPreferences.PREFERRED_ENCODINGS),
	LOG_LEVEL(TcPreferences.LOG_LEVEL),
	LOG_BUFFER_SIZE(TcPreferences.LOG_BUFFER_SIZE),
	CUSTOM_SHELL(TcPreferences.CUSTOM_SHELL),
	USE_CUSTOM_SHELL(TcPreferences.USE_CUSTOM_SHELL),
	SHELL_HISTORY_SIZE(TcPreferences.SHELL_HISTORY_SIZE),
	SHELL_ENCODING(TcPreferences.SHELL_ENCODING),
	AUTODETECT_SHELL_ENCODING(TcPreferences.AUTODETECT_SHELL_ENCODING),
	SMTP_SERVER(TcPreferences.SMTP_SERVER),
	SMTP_PORT(TcPreferences.SMTP_PORT),
	MAIL_SENDER_NAME(TcPreferences.MAIL_SENDER_NAME),
	MAIL_SENDER_ADDRESS(TcPreferences.MAIL_SENDER_ADDRESS),
	COMMAND_BAR_VISIBLE(TcPreferences.COMMAND_BAR_VISIBLE),
	COMMAND_BAR_ICON_SCALE(TcPreferences.COMMAND_BAR_ICON_SCALE),
	STATUS_BAR_VISIBLE(TcPreferences.STATUS_BAR_VISIBLE),
	TOOLBAR_VISIBLE(TcPreferences.TOOLBAR_VISIBLE),
	TOOLBAR_ICON_SCALE(TcPreferences.TOOLBAR_ICON_SCALE),
	VOLUME_EXCLUDE_REGEXP(TcPreferences.VOLUME_EXCLUDE_REGEXP),
	SHOW_HIDDEN_FILES(TcPreferences.SHOW_HIDDEN_FILES),
	SHOW_DS_STORE_FILES(TcPreferences.SHOW_DS_STORE_FILES),
	SHOW_SYSTEM_FOLDERS(TcPreferences.SHOW_SYSTEM_FOLDERS),
	TABLE_ICON_SCALE(TcPreferences.TABLE_ICON_SCALE),
	AUTO_SIZE_COLUMNS(TcPreferences.AUTO_SIZE_COLUMNS),
	USE_SYSTEM_FILE_ICONS(TcPreferences.USE_SYSTEM_FILE_ICONS),
	SHOW_FOLDERS_FIRST(TcPreferences.SHOW_FOLDERS_FIRST),
	FOLDERS_ALWAYS_ALPHABETICAL(TcPreferences.FOLDERS_ALWAYS_ALPHABETICAL),
	SHOW_QUICK_SEARCH_MATCHES_FIRST(TcPreferences.SHOW_QUICK_SEARCH_MATCHES_FIRST),
	QUICK_SEARCH_TIMEOUT(TcPreferences.QUICK_SEARCH_TIMEOUT),
	CD_FOLLOWS_SYMLINKS(TcPreferences.CD_FOLLOWS_SYMLINKS),
	USE_BRUSHED_METAL(TcPreferences.USE_BRUSHED_METAL),
	USE_SCREEN_MENU_BAR(TcPreferences.USE_SCREEN_MENU_BAR),
	STARTUP_FOLDERS(TcPreferences.STARTUP_FOLDERS),
	LEFT_CUSTOM_FOLDER(TcPreferences.LEFT_CUSTOM_FOLDER),
	RIGHT_CUSTOM_FOLDER(TcPreferences.RIGHT_CUSTOM_FOLDER),
	REFRESH_CHECK_PERIOD(TcPreferences.REFRESH_CHECK_PERIOD),
	WAIT_AFTER_REFRESH(TcPreferences.WAIT_AFTER_REFRESH),
	PROGRESS_DIALOG_EXPANDED(TcPreferences.PROGRESS_DIALOG_EXPANDED),
	PROGRESS_DIALOG_CLOSE_WHEN_FINISHED(TcPreferences.PROGRESS_DIALOG_CLOSE_WHEN_FINISHED),
	THEME_TYPE(TcPreferences.THEME_TYPE),
	THEME_NAME(TcPreferences.THEME_NAME),
    SYNTAX_THEME_NAME(TcPreferences.SYNTAX_THEME_NAME),
	ENABLE_BONJOUR_DISCOVERY(TcPreferences.ENABLE_BONJOUR_DISCOVERY),
	LIST_HIDDEN_FILES(TcPreferences.LIST_HIDDEN_FILES),
	SMB_LM_COMPATIBILITY(TcPreferences.SMB_LM_COMPATIBILITY),
	SMB_USE_EXTENDED_SECURITY(TcPreferences.SMB_USE_EXTENDED_SECURITY),
	SHOW_TAB_HEADER(TcPreferences.SHOW_SINGLE_TAB_HEADER),
	CALCULATE_FOLDER_SIZE_ON_MARK(TcPreferences.CALCULATE_FOLDER_SIZE_ON_MARK),
    FILE_GROUP_1_MASK(TcPreferences.FILE_GROUP_1_MASK),
    FILE_GROUP_2_MASK(TcPreferences.FILE_GROUP_2_MASK),
    FILE_GROUP_3_MASK(TcPreferences.FILE_GROUP_3_MASK),
    FILE_GROUP_4_MASK(TcPreferences.FILE_GROUP_4_MASK),
    FILE_GROUP_5_MASK(TcPreferences.FILE_GROUP_5_MASK),
    FILE_GROUP_6_MASK(TcPreferences.FILE_GROUP_6_MASK),
    FILE_GROUP_7_MASK(TcPreferences.FILE_GROUP_7_MASK),
    FILE_GROUP_8_MASK(TcPreferences.FILE_GROUP_8_MASK),
    FILE_GROUP_9_MASK(TcPreferences.FILE_GROUP_9_MASK),
    FILE_GROUP_10_MASK(TcPreferences.FILE_GROUP_10_MASK),
    CUSTOM_EXTERNAL_TERMINAL(TcPreferences.CUSTOM_EXTERNAL_TERMINAL),
    USE_CUSTOM_EXTERNAL_TERMINAL(TcPreferences.USE_CUSTOM_EXTERNAL_TERMINAL),
    TERMINAL_SHELL(TcPreferences.TERMINAL_SHELL),
    TERMINAL_USE_CUSTOM_SHELL(TcPreferences.TERMINAL_USE_CUSTOM_SHELL),
	FIND_FILE_ENCODING(TcPreferences.FIND_FILE_ENCODING),
	FIND_FILE_SUBDIRECTORIES(TcPreferences.FIND_FILE_SUBDIRECTORIES),
	FIND_FILE_ARCHIVES(TcPreferences.FIND_FILE_ARCHIVES),
	FIND_FILE_IGNORE_HIDDEN(TcPreferences.FIND_FILE_IGNORE_HIDDEN),
	FIND_FILE_CASE_SENSITIVE(TcPreferences.FIND_FILE_CASE_SENSITIVE),
	FIND_FILE_SEARCH_HEX(TcPreferences.FIND_FILE_SEARCH_HEX);



    private String label;
	
	TcPreference(String label) {
		this.label = label;
	}
	
	@Override
	public String toString() {
		return label;
	}
}
